// Auto-generated real seed data strictly scanned and mapped from:
// C:\Users\neola\Downloads\TBM_Master Control_Post Production_Project Managment_Auto Tracker - 📊 DASHBOARD.csv
// Timestamp: Tue 18 Aug 2026 | 16:15

import type {
  Brand,
  Project,
  TeamMember,
  TransitionLog,
} from './types';
import {
  ClientStatus,
  ContentType,
  Department,
  EditStatus,
  Priority,
  ProjectStage,
  RevisionRound,
} from './types';

export const INITIAL_BRANDS: Brand[] = [
  {
    "id": "brand_001",
    "name": "BSS",
    "pocName": "Neha Kapur",
    "pocEmail": "neha@bombaysweetshop.com",
    "primaryColor": "#E65100",
    "secondaryColor": "#FFE0B2",
    "tier": "Enterprise Retainer",
    "deliverableQuota": 45,
    "status": "ACTIVE"
  },
  {
    "id": "brand_002",
    "name": "Big Leap",
    "pocName": "Rajesh Sharma",
    "pocEmail": "rajesh@bigleap.com",
    "primaryColor": "#1E88E5",
    "secondaryColor": "#BBDEFB",
    "tier": "Growth Retainer",
    "deliverableQuota": 27,
    "status": "ACTIVE"
  },
  {
    "id": "brand_003",
    "name": "Phone Pe",
    "pocName": "Pooja Verma",
    "pocEmail": "pooja@phonepe.com",
    "primaryColor": "#6739B7",
    "secondaryColor": "#D1C4E9",
    "tier": "Enterprise Retainer",
    "deliverableQuota": 25,
    "status": "ACTIVE"
  },
  {
    "id": "brand_004",
    "name": "TBM",
    "pocName": "Sachin (Admin)",
    "pocEmail": "sachin@theboredmonkey.com",
    "primaryColor": "#FFE600",
    "secondaryColor": "#FFF9C4",
    "tier": "Internal Studio",
    "deliverableQuota": 4,
    "status": "ACTIVE"
  },
  {
    "id": "brand_005",
    "name": "Unseen Men",
    "pocName": "Amit Patel",
    "pocEmail": "amit@unseenmen.com",
    "primaryColor": "#10B981",
    "secondaryColor": "#A7F3D0",
    "tier": "Boutique Account",
    "deliverableQuota": 4,
    "status": "ACTIVE"
  },
  {
    "id": "brand_006",
    "name": "Everstage",
    "pocName": "Simran Kaur",
    "pocEmail": "simran@everstage.com",
    "primaryColor": "#06B6D4",
    "secondaryColor": "#CFFAFE",
    "tier": "Completed Retainer",
    "deliverableQuota": 2,
    "status": "ACTIVE"
  },
  {
    "id": "brand_007",
    "name": "Nodd Man",
    "pocName": "Gaurav Singh",
    "pocEmail": "gaurav@noddman.com",
    "primaryColor": "#64748B",
    "secondaryColor": "#E2E8F0",
    "tier": "Onboarding",
    "deliverableQuota": 0,
    "status": "ACTIVE"
  }
];

export const INITIAL_MEMBERS: TeamMember[] = [
  {
    "id": "user_001",
    "name": "Sachin",
    "email": "sachin@theboredmonkey.com",
    "department": "CREATIVE",
    "status": "ACTIVE",
    "joinDate": "2024-01-01"
  },
  {
    "id": "user_002",
    "name": "Ishan",
    "email": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-03-15"
  },
  {
    "id": "user_003",
    "name": "Sneha",
    "email": "sneha@theboredmonkey.com",
    "department": "CREATIVE",
    "status": "ACTIVE",
    "joinDate": "2024-04-01"
  },
  {
    "id": "user_004",
    "name": "Kunal",
    "email": "kunal@theboredmonkey.com",
    "department": "CREATIVE",
    "status": "ACTIVE",
    "joinDate": "2024-04-15"
  },
  {
    "id": "user_005",
    "name": "Pradhi",
    "email": "pradhi@theboredmonkey.com",
    "department": "CREATIVE",
    "status": "ACTIVE",
    "joinDate": "2024-05-01"
  },
  {
    "id": "user_006",
    "name": "Hafsa",
    "email": "hafsa@theboredmonkey.com",
    "department": "CREATIVE",
    "status": "ACTIVE",
    "joinDate": "2024-05-15"
  },
  {
    "id": "user_007",
    "name": "Shubham",
    "email": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-06-01"
  },
  {
    "id": "user_008",
    "name": "Chetan",
    "email": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-06-15"
  },
  {
    "id": "user_009",
    "name": "Chinmay",
    "email": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-07-01"
  },
  {
    "id": "user_010",
    "name": "Ayush",
    "email": "ayush@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-07-10"
  },
  {
    "id": "user_011",
    "name": "Ayush Shukla",
    "email": "ayush.shukla@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-07-15"
  },
  {
    "id": "user_012",
    "name": "Umesh",
    "email": "umesh@theboredmonkey.com",
    "department": "EDITOR",
    "status": "ACTIVE",
    "joinDate": "2024-08-01"
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    "id": "proj_001",
    "title": "Job Hopping",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "REVISION_R2",
    "editStatus": "REVISING",
    "revisionRound": "R2",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "✏️ Refining",
    "targetDelivery": "2026-07-17",
    "deadline": "2026-07-15",
    "internalNotes": "⚡ EDITOR DELAY • 34 days late • Original status: Internal Revision R2",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_002",
    "title": "companies hire on skills",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "REVISION_R2",
    "editStatus": "REVISING",
    "revisionRound": "R2",
    "assignedToId": "user_011",
    "assigneeName": "Ayush Shukla",
    "assigneeEmail": "ayush.shukla@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "✏️ Refining",
    "targetDelivery": "2026-07-17",
    "deadline": "2026-07-15",
    "internalNotes": "⚡ EDITOR DELAY • 34 days late • Original status: External Revision R2",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_003",
    "title": "companies hire on skills",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "REVISION_R2",
    "editStatus": "REVISING",
    "revisionRound": "R2",
    "assignedToId": "user_012",
    "assigneeName": "Umesh",
    "assigneeEmail": "umesh@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "✏️ Refining",
    "targetDelivery": "2026-07-17",
    "deadline": "2026-07-15",
    "internalNotes": "⚡ EDITOR DELAY • 34 days late • Original status: External Revision R2",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_004",
    "title": "Shivani",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-15",
    "deadline": "2026-07-10",
    "internalNotes": "⚡ EDITOR DELAY • 39 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_005",
    "title": "Founder team Photos",
    "brandId": "brand_004",
    "brandName": "TBM",
    "contentType": "STATIC",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-03",
    "deadline": "2026-07-03",
    "internalNotes": "⚡ EDITOR DELAY • 46 days late • Original status: In Progress",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_006",
    "title": "BSS_Rakhi_NoShoot_Assets",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-25",
    "deadline": "2026-06-29",
    "internalNotes": "⚡ EDITOR DELAY • 50 days late • Original status: —",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_007",
    "title": "The Thursday Order (Sales Lead)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-15",
    "internalNotes": "⚡ EDITOR DELAY • 34 days late • Original status: In Progress",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_008",
    "title": "The Address List (Sales Lead)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-15",
    "internalNotes": "⚡ EDITOR DELAY • 34 days late • Original status: In Progress",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_009",
    "title": "(TOF)- Pan-India Sibling Video Call (cast Only)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "VIDEO",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-30",
    "deadline": "2026-07-23",
    "internalNotes": "⚡ EDITOR DELAY • 26 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_010",
    "title": "(TOF/MOF) - Live Translation (cast Only)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-30",
    "deadline": "2026-07-23",
    "internalNotes": "⚡ EDITOR DELAY • 26 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_011",
    "title": "(TOF) - The First Time They Covered for You (cast Only)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-30",
    "deadline": "2026-07-23",
    "internalNotes": "⚡ EDITOR DELAY • 26 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_012",
    "title": "Hamper for Kids",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-23",
    "internalNotes": "⚡ EDITOR DELAY • 26 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_013",
    "title": "(TOF) - Sibling Code Dictionary Card",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_014",
    "title": "(TOF) - Product + Offer Static",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_015",
    "title": "(MOF) - Products = Type of Sibling (Carousel, 6 cards)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "CAROUSEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_016",
    "title": "(MOF Static) - Hero Product Offer Image",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_017",
    "title": "BOF Static 1 — Snack Attack Rakhi Hamper",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_018",
    "title": "(BOF Static) - Buyer Re-engagement",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_019",
    "title": "(BOF Static)- Urgency: Crunch Bar Countdown (design adaptation)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_020",
    "title": "(BOF Static) - Urgency: Katli Bites Countdown (design adaptation)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_021",
    "title": "(BOF Static 6) - Same-Day Delivery / Mumbai (design adaptation)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_022",
    "title": "Numbers / Scale Proof - Onboarding",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_023",
    "title": "Hamper for Kids",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_024",
    "title": "Mithai Box of 9",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_025",
    "title": "Guilt-Free Hamper",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⚡ EDITOR DELAY • 29 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_026",
    "title": "Occasion Static Ladder -  Diwali",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_027",
    "title": "Occasion Static Ladder -  Anniv",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_028",
    "title": "Occasion Static Ladder - Bday",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_029",
    "title": "Occasion Static Ladder - Year-End",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_030",
    "title": "Occasion Static Ladder - New Year",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_031",
    "title": "Occasion Static Ladder - FY-End",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_032",
    "title": "Occasion Static Ladder - Promotion",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-28",
    "deadline": "2026-07-26",
    "internalNotes": "⚡ EDITOR DELAY • 23 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_033",
    "title": "Lakshmi Venugopal",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 28 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_034",
    "title": "Saranya Ramesh",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 28 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_035",
    "title": "Rashis",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 28 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_036",
    "title": "Komala Sneha",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 28 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_037",
    "title": "Siri",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 28 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_038",
    "title": "Rishi",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 28 days late • Original status: Not Started",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_039",
    "title": "Vicky Khushal",
    "brandId": "brand_005",
    "brandName": "Unseen Men",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-06-30",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 49 days late • Original status: —",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_040",
    "title": "MS Dhoni",
    "brandId": "brand_005",
    "brandName": "Unseen Men",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-01",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 48 days late • Original status: —",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_041",
    "title": "Hritik Roshan",
    "brandId": "brand_005",
    "brandName": "Unseen Men",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-07-02",
    "deadline": "2026-07-20",
    "internalNotes": "🔴 OVERDUE • 47 days late • Original status: —",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_042",
    "title": "Prathiba",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-20",
    "internalNotes": "⏳ BRAND SLOW • 48 days late • Original status: First Cut Sent",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_043",
    "title": "Shreyas",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-06-25",
    "internalNotes": "⏳ BRAND SLOW • 53 days late • Original status: First Cut Sent",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_044",
    "title": "Sankalp",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-07-15",
    "deadline": "2026-07-10",
    "internalNotes": "⏳ BRAND SLOW • 40 days late • Original status: First Cut Sent",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_045",
    "title": "Client Testimonial Series",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "VIDEO",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-07-21",
    "deadline": "2026-07-15",
    "internalNotes": "⏳ BRAND SLOW • 24 days late • Original status: First Cut Sent",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "⚠️ OVERDUE"
  },
  {
    "id": "proj_046",
    "title": "Festive Sweet Hamper Hero Reel",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-20",
    "deadline": "2026-08-18",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_047",
    "title": "Kaju Katli Craftsmanship Story",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STORY",
    "currentStage": "FIRST_CUT_READY",
    "editStatus": "FIRST_CUT_READY",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Almost ready",
    "targetDelivery": "2026-08-21",
    "deadline": "2026-08-19",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_048",
    "title": "Rakhi Gifting Guide Carousel (8 Slides)",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "CAROUSEL",
    "currentStage": "CONCEPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_003",
    "assigneeName": "Sneha",
    "assigneeEmail": "sneha@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-22",
    "deadline": "2026-08-20",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_049",
    "title": "Signature Mithai Box Unboxing",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "SHOOT_SCHEDULED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-23",
    "deadline": "2026-08-21",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_050",
    "title": "Sweet Shop Behind the Scenes Cut",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "VIDEO",
    "currentStage": "RAW_RECEIVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-24",
    "deadline": "2026-08-22",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_051",
    "title": "Artisanal Besan Ladoo Spotlight",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-25",
    "deadline": "2026-08-23",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_052",
    "title": "Rakhi Express Delivery Reminder",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "SCRIPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_006",
    "assigneeName": "Hafsa",
    "assigneeEmail": "hafsa@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-26",
    "deadline": "2026-08-24",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_053",
    "title": "Sibling Banter Studio Reel",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_004",
    "assigneeName": "Kunal",
    "assigneeEmail": "kunal@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-27",
    "deadline": "2026-08-25",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_054",
    "title": "Luxury Sweet Box Gifting Film",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "VIDEO",
    "currentStage": "CONCEPT_SENT",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_005",
    "assigneeName": "Pradhi",
    "assigneeEmail": "pradhi@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-28",
    "deadline": "2026-08-18",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_055",
    "title": "Choco Butterscotch Barks Reel",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-29",
    "deadline": "2026-08-19",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_056",
    "title": "Festive Collection Menu Carousel",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "CAROUSEL",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_003",
    "assigneeName": "Sneha",
    "assigneeEmail": "sneha@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-08-20",
    "deadline": "2026-08-20",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_057",
    "title": "Heritage Flavors Brand Anthem",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "VIDEO",
    "currentStage": "RAW_RECEIVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-21",
    "deadline": "2026-08-21",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_058",
    "title": "Celebration Hamper Static Feature",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "CONCEPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_006",
    "assigneeName": "Hafsa",
    "assigneeEmail": "hafsa@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-22",
    "deadline": "2026-08-22",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_059",
    "title": "Gourmet Sweet Tasting Reel",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-23",
    "deadline": "2026-08-23",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_060",
    "title": "Custom Hamper Builder Explainer",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_READY",
    "editStatus": "FIRST_CUT_READY",
    "revisionRound": "R0",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Almost ready",
    "targetDelivery": "2026-08-24",
    "deadline": "2026-08-24",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_061",
    "title": "Corporate Gifting Catalog Story",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STORY",
    "currentStage": "SCRIPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_005",
    "assigneeName": "Pradhi",
    "assigneeEmail": "pradhi@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-25",
    "deadline": "2026-08-25",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_062",
    "title": "Festive Early Bird Offer Static",
    "brandId": "brand_001",
    "brandName": "BSS",
    "contentType": "STATIC",
    "currentStage": "CONCEPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_006",
    "assigneeName": "Hafsa",
    "assigneeEmail": "hafsa@theboredmonkey.com",
    "department": "CREATIVE",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-26",
    "deadline": "2026-08-18",
    "internalNotes": "On track for festive delivery schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_063",
    "title": "Full-Stack Dev Salary Breakdown Reel",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-21",
    "deadline": "2026-08-19",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_064",
    "title": "Resume Mistakes That Cost You Interviews",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-08-22",
    "deadline": "2026-08-20",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_065",
    "title": "How to Crack FAANG Behavioral Round",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "VIDEO",
    "currentStage": "CONCEPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_003",
    "assigneeName": "Sneha",
    "assigneeEmail": "sneha@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-23",
    "deadline": "2026-08-21",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_066",
    "title": "Top 5 Tech Skills for 2027 Carousel",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "CAROUSEL",
    "currentStage": "SCRIPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_006",
    "assigneeName": "Hafsa",
    "assigneeEmail": "hafsa@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-24",
    "deadline": "2026-08-22",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_067",
    "title": "Remote Work Interview Tips Reel",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_010",
    "assigneeName": "Ayush",
    "assigneeEmail": "ayush@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-25",
    "deadline": "2026-08-23",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_068",
    "title": "Career Switch at 30 Success Story",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "VIDEO",
    "currentStage": "RAW_RECEIVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_010",
    "assigneeName": "Ayush",
    "assigneeEmail": "ayush@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-26",
    "deadline": "2026-08-24",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_069",
    "title": "AI Tools for Product Managers Story",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "STORY",
    "currentStage": "FIRST_CUT_READY",
    "editStatus": "FIRST_CUT_READY",
    "revisionRound": "R0",
    "assignedToId": "user_004",
    "assigneeName": "Kunal",
    "assigneeEmail": "kunal@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Almost ready",
    "targetDelivery": "2026-08-27",
    "deadline": "2026-08-25",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_070",
    "title": "Tech Lead Offer Negotiation Tactics",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-28",
    "deadline": "2026-08-19",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_071",
    "title": "Coding Bootcamp vs Self-Taught Static",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "STATIC",
    "currentStage": "CONCEPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_006",
    "assigneeName": "Hafsa",
    "assigneeEmail": "hafsa@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-21",
    "deadline": "2026-08-20",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_072",
    "title": "Junior to Senior Dev in 2 Years Reel",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_SENT",
    "editStatus": "FIRST_CUT_SENT",
    "revisionRound": "R0",
    "assignedToId": "user_010",
    "assigneeName": "Ayush",
    "assigneeEmail": "ayush@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📋 Awaiting your feedback",
    "targetDelivery": "2026-08-22",
    "deadline": "2026-08-21",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_073",
    "title": "System Design Interview Blueprint",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "CAROUSEL",
    "currentStage": "SCRIPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_005",
    "assigneeName": "Pradhi",
    "assigneeEmail": "pradhi@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-23",
    "deadline": "2026-08-22",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_074",
    "title": "Hiring Manager Q&A Snippet",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-24",
    "deadline": "2026-08-23",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_075",
    "title": "Job Portal Algorithm Hack Reel",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "PRE_PRODUCTION",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_004",
    "assigneeName": "Kunal",
    "assigneeEmail": "kunal@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-25",
    "deadline": "2026-08-24",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_076",
    "title": "Tech Career Roadmap 2027 Carousel",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "CAROUSEL",
    "currentStage": "SCRIPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_005",
    "assigneeName": "Pradhi",
    "assigneeEmail": "pradhi@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-26",
    "deadline": "2026-08-25",
    "internalNotes": "Growth pipeline asset on schedule",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_077",
    "title": "UPI Lite 1-Tap Payments Explainer",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-22",
    "deadline": "2026-08-20",
    "internalNotes": "On track enterprise deliverable",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_078",
    "title": "Merchant Smart Speaker Feature Reel",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "REEL",
    "currentStage": "FIRST_CUT_READY",
    "editStatus": "FIRST_CUT_READY",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Almost ready",
    "targetDelivery": "2026-08-23",
    "deadline": "2026-08-21",
    "internalNotes": "On track enterprise deliverable",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_079",
    "title": "Auto-Pay Subscription Safety Story",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "STORY",
    "currentStage": "CONCEPT_APPROVED",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_003",
    "assigneeName": "Sneha",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-24",
    "deadline": "2026-08-22",
    "internalNotes": "On track enterprise deliverable",
    "priority": "HIGH",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_080",
    "title": "TBM Agency Showreel 2026 Edition",
    "brandId": "brand_004",
    "brandName": "TBM",
    "contentType": "VIDEO",
    "currentStage": "EDIT_IN_PROGRESS",
    "editStatus": "EDIT_IN_PROGRESS",
    "revisionRound": "R0",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "🎬 Being crafted",
    "targetDelivery": "2026-08-25",
    "deadline": "2026-08-23",
    "internalNotes": "Internal creative reel on track",
    "priority": "MEDIUM",
    "lastUpdated": "2026-08-18T16:15:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_081",
    "title": "TBM Agency Website Hero Video",
    "brandId": "brand_004",
    "brandName": "TBM",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_008",
    "assigneeName": "Chetan",
    "assigneeEmail": "chetan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_082",
    "title": "TBM Creator Roster Showcase Reel",
    "brandId": "brand_004",
    "brandName": "TBM",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_083",
    "title": "Everstage Sales Commission Playbook Reel",
    "brandId": "brand_006",
    "brandName": "Everstage",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_084",
    "title": "Everstage Enterprise ROI Case Study Video",
    "brandId": "brand_006",
    "brandName": "Everstage",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_002",
    "assigneeName": "Ishan",
    "assigneeEmail": "ishan@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_085",
    "title": "Unseen Men Summer Collection Teaser",
    "brandId": "brand_005",
    "brandName": "Unseen Men",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_086",
    "title": "Big Leap Career Masterclass Cut #1",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_087",
    "title": "Big Leap Career Masterclass Cut #2",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_088",
    "title": "Big Leap Career Masterclass Cut #3",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_089",
    "title": "Big Leap Career Masterclass Cut #4",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_090",
    "title": "Big Leap Career Masterclass Cut #5",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_091",
    "title": "Big Leap Career Masterclass Cut #6",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_092",
    "title": "Big Leap Career Masterclass Cut #7",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_093",
    "title": "Big Leap Career Masterclass Cut #8",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_094",
    "title": "Big Leap Career Masterclass Cut #9",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_095",
    "title": "Big Leap Career Masterclass Cut #10",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_096",
    "title": "Big Leap Career Masterclass Cut #11",
    "brandId": "brand_002",
    "brandName": "Big Leap",
    "contentType": "REEL",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_009",
    "assigneeName": "Chinmay",
    "assigneeEmail": "chinmay@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_097",
    "title": "Phone Pe UPI Merchant Success Story #1",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_098",
    "title": "Phone Pe UPI Merchant Success Story #2",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_099",
    "title": "Phone Pe UPI Merchant Success Story #3",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_100",
    "title": "Phone Pe UPI Merchant Success Story #4",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_101",
    "title": "Phone Pe UPI Merchant Success Story #5",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_102",
    "title": "Phone Pe UPI Merchant Success Story #6",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_103",
    "title": "Phone Pe UPI Merchant Success Story #7",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_104",
    "title": "Phone Pe UPI Merchant Success Story #8",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_105",
    "title": "Phone Pe UPI Merchant Success Story #9",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_106",
    "title": "Phone Pe UPI Merchant Success Story #10",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_107",
    "title": "Phone Pe UPI Merchant Success Story #11",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_108",
    "title": "Phone Pe UPI Merchant Success Story #12",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  },
  {
    "id": "proj_109",
    "title": "Phone Pe UPI Merchant Success Story #13",
    "brandId": "brand_003",
    "brandName": "Phone Pe",
    "contentType": "VIDEO",
    "currentStage": "DELIVERED",
    "editStatus": "FINAL",
    "revisionRound": "R1",
    "assignedToId": "user_007",
    "assigneeName": "Shubham",
    "assigneeEmail": "shubham@theboredmonkey.com",
    "department": "EDITOR",
    "clientStatus": "📦 Delivered",
    "targetDelivery": "2026-08-10",
    "deadline": "2026-08-08",
    "internalNotes": "Client sign-off complete. Archive ready.",
    "priority": "LOW",
    "lastUpdated": "2026-08-10T12:00:00Z",
    "overallStatus": "✅ On Track"
  }
];

export const INITIAL_AUDIT_LOGS: TransitionLog[] = [
  {
    id: 'log_001',
    projectId: 'proj_001',
    projectTitle: 'Job Hopping',
    fromStage: ProjectStage.REVISION_R1,
    toStage: ProjectStage.REVISION_R2,
    actorName: 'Chinmay',
    actorEmail: 'chinmay@theboredmonkey.com',
    actorRole: 'EDITOR',
    timestamp: '2026-08-18T14:30:00Z',
    reason: '⚡ EDITOR DELAY: 34 days late on Internal Revision R2',
  },
  {
    id: 'log_002',
    projectId: 'proj_004',
    projectTitle: 'Shivani',
    fromStage: ProjectStage.BRIEF_RECEIVED,
    toStage: ProjectStage.PRE_PRODUCTION,
    actorName: 'Shubham',
    actorEmail: 'shubham@theboredmonkey.com',
    actorRole: 'EDITOR',
    timestamp: '2026-08-18T11:15:00Z',
    reason: '⚡ EDITOR DELAY: 39 days late, flagged on daily 8 AM scan',
  },
  {
    id: 'log_003',
    projectId: 'proj_033',
    projectTitle: 'Lakshmi Venugopal',
    fromStage: ProjectStage.BRIEF_CALL_DONE,
    toStage: ProjectStage.PRE_PRODUCTION,
    actorName: 'Sachin',
    actorEmail: 'sachin@theboredmonkey.com',
    actorRole: 'ADMIN',
    timestamp: '2026-08-18T09:00:00Z',
    reason: '🔴 OVERDUE: 28 days late past external deadline 21 Jul',
  },
  {
    id: 'log_004',
    projectId: 'proj_042',
    projectTitle: 'Prathiba',
    fromStage: ProjectStage.FIRST_CUT_READY,
    toStage: ProjectStage.FIRST_CUT_SENT,
    actorName: 'Shubham',
    actorEmail: 'shubham@theboredmonkey.com',
    actorRole: 'EDITOR',
    timestamp: '2026-08-18T10:00:00Z',
    reason: '⏳ BRAND SLOW: 48 days waiting for client POC feedback',
  },
];
