export interface OutreachPerformanceItem {
    id: string;
    poc: string;
    category: string;
    designation: string;
    channel: "LinkedIn" | "Email" | "Cold Call";
    step: string;
    sent: number;
    opened: number;
    replied: number;
    meetings: number;
    daysToReply: number;
    dealStage: "Deal Won" | "In Negotiation" | "Meeting Scheduled" | "No Deal Yet";
    lastActivity: string;
    status: "Working" | "Mixed" | "Not Working";
    why: string;
}

export const INITIAL_OUTREACH_PERFORMANCE_DATA: OutreachPerformanceItem[] = [
    {
        id: "perf_1",
        poc: "Haji Karim",
        category: "D2C Beauty",
        designation: "Founder/CEO",
        channel: "LinkedIn",
        step: "Msg 1 - Intro",
        sent: 40,
        opened: 30,
        replied: 11,
        meetings: 3,
        daysToReply: 1.2,
        dealStage: "In Negotiation",
        lastActivity: "Sep 5",
        status: "Working",
        why: "Founder-led angle + Atomberg proof point lands well; fast replies within 24h.",
    },
    {
        id: "perf_2",
        poc: "Haji Karim",
        category: "D2C Beauty",
        designation: "Founder/CEO",
        channel: "Email",
        step: "Msg 2 - Case Study",
        sent: 45,
        opened: 22,
        replied: 8,
        meetings: 2,
        daysToReply: 2.1,
        dealStage: "Meeting Scheduled",
        lastActivity: "Sep 6",
        status: "Working",
        why: "Case study follow-up converts founders who didn't reply to LinkedIn.",
    },
    {
        id: "perf_3",
        poc: "Haji Karim",
        category: "D2C Food & Bev",
        designation: "Marketing Head",
        channel: "Email",
        step: "Msg 1 - Intro",
        sent: 60,
        opened: 18,
        replied: 6,
        meetings: 1,
        daysToReply: 4.5,
        dealStage: "No Deal Yet",
        lastActivity: "Sep 3",
        status: "Not Working",
        why: "Generic pitch, no category-specific case study attached; low open rate.",
    },
    {
        id: "perf_4",
        poc: "Haji Karim",
        category: "Fintech",
        designation: "CMO",
        channel: "LinkedIn",
        step: "Msg 1 - Intro",
        sent: 40,
        opened: 29,
        replied: 11,
        meetings: 3,
        daysToReply: 1.5,
        dealStage: "Meeting Scheduled",
        lastActivity: "Sep 6",
        status: "Working",
        why: "Regional reach/salience narrative resonates with fintech CMOs post-funding news.",
    },
    {
        id: "perf_5",
        poc: "Snehal Maurya",
        category: "D2C Beauty",
        designation: "Brand Manager",
        channel: "LinkedIn",
        step: "Msg 1 - Intro",
        sent: 70,
        opened: 31,
        replied: 8,
        meetings: 2,
        daysToReply: 2.8,
        dealStage: "No Deal Yet",
        lastActivity: "Sep 4",
        status: "Mixed",
        why: "Good open rate but Brand Managers stall at approvals stage, need CMO co-sign.",
    },
    {
        id: "perf_6",
        poc: "Snehal Maurya",
        category: "Fashion/Apparel",
        designation: "Founder/CEO",
        channel: "LinkedIn",
        step: "Msg 1 - Intro",
        sent: 35,
        opened: 27,
        replied: 10,
        meetings: 3,
        daysToReply: 1.0,
        dealStage: "Meeting Scheduled",
        lastActivity: "Sep 7",
        status: "Working",
        why: "North India founder network warm intros converting fast via LinkedIn sequence.",
    },
    {
        id: "perf_7",
        poc: "Snehal Maurya",
        category: "Fashion/Apparel",
        designation: "Founder/CEO",
        channel: "Cold Call",
        step: "Msg 3 - Follow-up",
        sent: 20,
        opened: 20,
        replied: 4,
        meetings: 1,
        daysToReply: 0.2,
        dealStage: "In Negotiation",
        lastActivity: "Sep 7",
        status: "Working",
        why: "Calling founders directly after 2 unanswered messages closes the loop fast.",
    },
    {
        id: "perf_8",
        poc: "Snehal Maurya",
        category: "Home & Living",
        designation: "Marketing Head",
        channel: "Email",
        step: "Msg 1 - Intro",
        sent: 45,
        opened: 14,
        replied: 3,
        meetings: 0,
        daysToReply: 5.2,
        dealStage: "No Deal Yet",
        lastActivity: "Sep 2",
        status: "Not Working",
        why: "Category has long buying cycles; single-touch outreach insufficient, needs nurture sequence.",
    },
    {
        id: "perf_9",
        poc: "Suraj Maurya",
        category: "Healthcare/Wellness",
        designation: "Growth Head",
        channel: "LinkedIn",
        step: "Msg 1 - Intro",
        sent: 50,
        opened: 34,
        replied: 13,
        meetings: 4,
        daysToReply: 1.4,
        dealStage: "Deal Won",
        lastActivity: "Sep 6",
        status: "Working",
        why: "GarbhaGudi case study (₹0.21 CPV, 85K+ shares) is a strong trigger for wellness Growth Heads.",
    },
    {
        id: "perf_10",
        poc: "Suraj Maurya",
        category: "D2C Food & Bev",
        designation: "Founder/CEO",
        channel: "Email",
        step: "Msg 2 - Case Study",
        sent: 65,
        opened: 24,
        replied: 9,
        meetings: 2,
        daysToReply: 3.3,
        dealStage: "No Deal Yet",
        lastActivity: "Sep 5",
        status: "Mixed",
        why: "Replies good, but founders want custom deck before call — slows conversion to meeting.",
    },
    {
        id: "perf_11",
        poc: "Suraj Maurya",
        category: "Fintech",
        designation: "Brand Manager",
        channel: "Email",
        step: "Msg 1 - Intro",
        sent: 38,
        opened: 9,
        replied: 2,
        meetings: 0,
        daysToReply: 6.0,
        dealStage: "No Deal Yet",
        lastActivity: "Sep 1",
        status: "Not Working",
        why: "Brand Managers in fintech have no budget authority; wrong designation for cold outreach.",
    },
    {
        id: "perf_12",
        poc: "Karim Beldaar",
        category: "D2C Beauty",
        designation: "CMO",
        channel: "LinkedIn",
        step: "Msg 1 - Intro",
        sent: 48,
        opened: 33,
        replied: 12,
        meetings: 3,
        daysToReply: 1.1,
        dealStage: "Meeting Scheduled",
        lastActivity: "Sep 6",
        status: "Working",
        why: "South India creator network proof point is a strong differentiator for beauty CMOs.",
    },
    {
        id: "perf_13",
        poc: "Karim Beldaar",
        category: "Fashion/Apparel",
        designation: "Growth Head",
        channel: "Email",
        step: "Msg 1 - Intro",
        sent: 52,
        opened: 19,
        replied: 7,
        meetings: 1,
        daysToReply: 4.0,
        dealStage: "No Deal Yet",
        lastActivity: "Sep 4",
        status: "Mixed",
        why: "Decent reply rate but meetings drop off — need faster follow-up (currently 3-4 days gap).",
    },
    {
        id: "perf_14",
        poc: "Karim Beldaar",
        category: "Home & Living",
        designation: "Founder/CEO",
        channel: "Cold Call",
        step: "Msg 3 - Follow-up",
        sent: 33,
        opened: 33,
        replied: 2,
        meetings: 0,
        daysToReply: 0.5,
        dealStage: "No Deal Yet",
        lastActivity: "Aug 30",
        status: "Not Working",
        why: "Category cold-email library outdated (built for festive season); needs refresh.",
    },
];

export const PREV_WEEK_STATS = {
    sent: 601,
    openRate: 46.2,
    replyRate: 13.1,
    meetings: 19,
    deals: 1,
    daysToReply: 3.4,
};

export const TREND_DATA = {
    labels: ["Sep 1", "Sep 2", "Sep 3", "Sep 4", "Sep 5", "Sep 6", "Sep 7"],
    sent: [85, 92, 78, 110, 120, 95, 60],
    replied: [9, 11, 7, 15, 22, 18, 10],
};
