/**
 * The Bored Monkey (TBM) - System Configuration Constants
 */
export const TBM_CONFIG = {
  TIMEZONE: 'Asia/Kolkata',
  STALE_DAYS: 1,
  ESCALATE_AFTER: 3,
  ARCHIVE_AFTER_DAYS: 30,
  DEADLINE_ALERT_DAYS: 3,
  BRAND_REVIEW_NUDGE_DAYS: 2,
  ADMIN_EMAIL: 'sachin@theboredmonkey.com',
  ADMIN_NAME: 'Sachin',
  DOMAIN: 'theboredmonkey.com',
  SMTP_FROM: 'noreply@theboredmonkey.com',
} as const;

export enum ProjectStage {
  BRIEF_RECEIVED = 'BRIEF_RECEIVED',
  BRIEF_CALL_DONE = 'BRIEF_CALL_DONE',
  CONCEPT_IN_PROGRESS = 'CONCEPT_IN_PROGRESS',
  CONCEPT_SENT = 'CONCEPT_SENT',
  CONCEPT_APPROVED = 'CONCEPT_APPROVED',
  SCRIPT_IN_PROGRESS = 'SCRIPT_IN_PROGRESS',
  SCRIPT_APPROVED = 'SCRIPT_APPROVED',
  PRE_PRODUCTION = 'PRE_PRODUCTION',
  SHOOT_SCHEDULED = 'SHOOT_SCHEDULED',
  SHOOT_DONE = 'SHOOT_DONE',
  RAW_RECEIVED = 'RAW_RECEIVED',
  EDIT_IN_PROGRESS = 'EDIT_IN_PROGRESS',
  FIRST_CUT_READY = 'FIRST_CUT_READY',
  FIRST_CUT_SENT = 'FIRST_CUT_SENT',
  CLIENT_FEEDBACK = 'CLIENT_FEEDBACK',
  REVISION_R1 = 'REVISION_R1',
  REVISION_R2 = 'REVISION_R2',
  REVISION_R3 = 'REVISION_R3',
  FINAL_APPROVED = 'FINAL_APPROVED',
  DELIVERED = 'DELIVERED',
  INVOICED = 'INVOICED',
  CLOSED = 'CLOSED',
}

export enum RevisionRound {
  R0 = 'R0',
  R1 = 'R1',
  R2 = 'R2',
  R3 = 'R3',
  R4_PLUS = 'R4_PLUS',
}

export enum Priority {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum Department {
  CREATIVE = 'CREATIVE',
  EDITOR = 'EDITOR',
  PRODUCTION = 'PRODUCTION',
}

export enum ContentType {
  REEL = 'REEL',
  VIDEO = 'VIDEO',
  CAROUSEL = 'CAROUSEL',
  STATIC = 'STATIC',
  STORY = 'STORY',
}

export enum EditStatus {
  EDIT_IN_PROGRESS = 'EDIT_IN_PROGRESS',
  FIRST_CUT_READY = 'FIRST_CUT_READY',
  FIRST_CUT_SENT = 'FIRST_CUT_SENT',
  REVISING = 'REVISING',
  FINAL = 'FINAL',
}

export enum ClientStatus {
  BEING_CRAFTED = 'BEING_CRAFTED',
  ALMOST_READY = 'ALMOST_READY',
  AWAITING_FEEDBACK = 'AWAITING_FEEDBACK',
  REFINING = 'REFINING',
  APPROVED = 'APPROVED',
  DELIVERED = 'DELIVERED',
  COMPLETE = 'COMPLETE',
}
